### ISSUE TITLE
Get test coverage of our tests

### ISSUE THREAD

**Issue by vhellem** [difi/dc16-digitalcitizen#239]

**Comment by Kumiii** [comment]
Looks like it fails because app.js is not a DOM-element, even when PhantomJS is used as browser. 
To get this far in the test, we need to add the following to karma.conf.js:
```
plugins: [
            require("karma-webpack"), 'karma-jasmine',
            'karma-chrome-launcher',
            require("karma-coverage"),
            require("karma-sourcemap-loader"),
            require("karma-phantomjs-launcher")
        ]
```
And the files we want to test the coverage for. This is where it fails for now.
